import type { ProjectGraphTableFieldPlan } from './types';

export interface ConstructionOrgTableDefinition {
  id: string;
  title: string;
  moduleTitles: string[];
  required: boolean;
  triggerKeywords: string[];
  fields: ProjectGraphTableFieldPlan[];
}

function field(name: string, sourceDomain: ProjectGraphTableFieldPlan['sourceDomain'], sourceHint: string, fallbackPolicy: ProjectGraphTableFieldPlan['fallbackPolicy'], required = true): ProjectGraphTableFieldPlan {
  return { name, sourceDomain, sourceHint, fallbackPolicy, required };
}

export const CONSTRUCTION_ORG_TABLE_CATALOG: ConstructionOrgTableDefinition[] = [
  {
    id: 'project-overview',
    title: '工程概况一览表',
    moduleTitles: ['编制说明与工程概况'],
    required: true,
    triggerKeywords: ['工程概况', '概况', '编制说明', '建设规模', '工期'],
    fields: [
      field('工程名称', 'project', '从项目名称、招标范围提取', 'projectFactOnly'),
      field('建设地点', 'project', '从建设地点资料提取', 'projectFactOnly'),
      field('建设规模', 'project', '建筑面积、结构形式、层数等从资料提取', 'projectFactOnly'),
      field('计划工期', 'schedule', '从工期节点或资料提取', 'projectFactOnly'),
      field('质量标准', 'standards', '从招标要求或质量标准提取', 'standardAllowed'),
      field('招标范围', 'requirements', '从招标范围与工作内容提取', 'deriveFromContext'),
    ],
  },
  {
    id: 'project-difficulty',
    title: '项目重难点识别表',
    moduleTitles: ['编制说明与工程概况'],
    required: true,
    triggerKeywords: ['重点', '难点', '重难点', '风险'],
    fields: [
      field('重难点', 'risks', '从图谱风险、现场条件、项目要求中提取', 'deriveFromContext'),
      field('形成原因', 'siteConditions', '结合现场条件、工期、周边环境、施工范围说明', 'deriveFromContext'),
      field('影响范围', 'works', '关联受影响的分部分项、区域、工序或周边对象', 'deriveFromContext'),
      field('专项措施', 'methods', '结合工艺方法、风险 mitigation 和标准措施填写', 'standardAllowed'),
      field('责任岗位', 'standard', '按项目经理、技术负责人、施工员、安全员、质量员等职责填写', 'standardAllowed'),
    ],
  },
  {
    id: 'site-layout-zones',
    title: '现场总平面分区布置表',
    moduleTitles: ['施工现场平面布置与临设管理'],
    required: true,
    triggerKeywords: ['总平面', '平面布置', '临设', '材料堆场'],
    fields: [
      field('区域名称', 'siteConditions', '从现场条件、临设、加工区、办公生活区等识别', 'deriveFromContext'),
      field('位置', 'siteConditions', '从现场平面、道路、场地条件或资料描述提取', 'projectFactOnly', false),
      field('功能', 'standard', '按办公、生活、加工、堆放、通行等功能填写', 'standardAllowed'),
      field('面积', 'project', '仅资料明确时填写，不得编造', 'projectFactOnly', false),
      field('搭设标准', 'standards', '按临设、安全文明、消防、环保标准填写', 'standardAllowed'),
      field('拆除时间', 'schedule', '结合施工阶段或竣工清理阶段填写', 'deriveFromContext', false),
    ],
  },
  {
    id: 'temporary-electric-load',
    title: '临时用电负荷统计表',
    moduleTitles: ['施工现场平面布置与临设管理'],
    required: true,
    triggerKeywords: ['临时用电', '临电', '三级配电', '设备功率'],
    fields: [
      field('设备名称', 'resources', '从设备资源、机械投入计划中提取', 'deriveFromContext'),
      field('功率', 'resources', '仅资料或设备参数明确时填写', 'projectFactOnly', false),
      field('数量', 'resources', '从设备数量或资源计划提取', 'projectFactOnly', false),
      field('总功率', 'resources', '仅功率和数量明确时计算，否则不编造', 'projectFactOnly', false),
      field('负荷等级', 'standard', '按临电管理和设备重要性判断', 'standardAllowed', false),
      field('检查频次', 'standards', '按临电巡查制度填写', 'standardAllowed'),
    ],
  },
  {
    id: 'progress-milestones',
    title: '关键施工节点控制计划表',
    moduleTitles: ['进度计划与工期保障'],
    required: true,
    triggerKeywords: ['进度', '工期', '节点', '计划'],
    fields: [
      field('关键节点', 'schedule', '从工期节点、里程碑、施工阶段提取', 'projectFactOnly'),
      field('计划完成时间', 'schedule', '仅资料明确时填写日期或工期节点', 'projectFactOnly', false),
      field('责任岗位', 'standard', '按施工组织管理职责填写', 'standardAllowed'),
      field('投入资源', 'resources', '关联劳动力、机械、材料资源', 'deriveFromContext'),
      field('检查频次', 'standard', '按日计划、周计划、月计划检查机制填写', 'standardAllowed'),
      field('滞后纠偏措施', 'methods', '结合资源调配、穿插施工和备用资源填写', 'standardAllowed'),
    ],
  },
  {
    id: 'equipment-plan',
    title: '主要施工机械设备投入计划表',
    moduleTitles: ['资源配置计划'],
    required: true,
    triggerKeywords: ['机械设备', '设备投入', '资源配置'],
    fields: [
      field('设备名称', 'resources', '从 equipment 类型资源提取', 'deriveFromContext'),
      field('规格型号', 'resources', '从资源规格型号提取', 'projectFactOnly', false),
      field('数量', 'resources', '从资源数量提取', 'projectFactOnly', false),
      field('使用阶段', 'schedule', '结合施工阶段和适用工程内容填写', 'deriveFromContext'),
      field('用途', 'works', '关联适用分部分项或工序', 'deriveFromContext'),
      field('进退场时间', 'schedule', '仅资料明确时填写，否则按施工阶段表达', 'deriveFromContext', false),
    ],
  },
  {
    id: 'labor-plan',
    title: '分阶段劳动力动态投入计划表',
    moduleTitles: ['资源配置计划'],
    required: true,
    triggerKeywords: ['劳动力', '人员投入', '班组'],
    fields: [
      field('施工阶段', 'schedule', '从施工阶段和进度节点提取', 'deriveFromContext'),
      field('工种', 'resources', '从 labor 类型资源、工序需求推导', 'deriveFromContext'),
      field('人数', 'resources', '仅资料明确时填写', 'projectFactOnly', false),
      field('主要工作内容', 'works', '关联对应分部分项工程', 'deriveFromContext'),
      field('调配原则', 'standard', '按工期节点、穿插施工和资源动态调配填写', 'standardAllowed'),
    ],
  },
  {
    id: 'quality-hidden-acceptance',
    title: '隐蔽工程验收清单表',
    moduleTitles: ['质量管理体系与质量保证措施'],
    required: true,
    triggerKeywords: ['隐蔽工程', '隐蔽验收', '质量验收'],
    fields: [
      field('隐蔽部位', 'works', '从分部分项工程、图纸做法和工序识别', 'deriveFromContext'),
      field('验收内容', 'methods', '结合工艺步骤和质量控制点填写', 'deriveFromContext'),
      field('验收时机', 'schedule', '按工序完成、覆盖前、下道工序前填写', 'standardAllowed'),
      field('验收要点', 'standards', '从验收规范、质量标准和材料要求提取', 'standardAllowed'),
      field('影像留存', 'standard', '按隐蔽验收资料归档要求填写', 'standardAllowed'),
    ],
  },
  {
    id: 'quality-common-defects',
    title: '质量通病防治清单表',
    moduleTitles: ['质量管理体系与质量保证措施'],
    required: true,
    triggerKeywords: ['质量通病', '防治', '质量控制'],
    fields: [
      field('通病问题', 'risks', '从质量风险、常见工序问题和项目类型推导', 'deriveFromContext'),
      field('产生原因', 'methods', '结合施工工艺、材料、环境和操作因素填写', 'deriveFromContext'),
      field('预防措施', 'methods', '按工艺控制、样板引路、材料复试等填写', 'standardAllowed'),
      field('整改标准', 'standards', '从验收规范和质量标准提取', 'standardAllowed'),
      field('复查频次', 'standard', '按质量检查制度填写', 'standardAllowed'),
    ],
  },
  {
    id: 'risk-grade-control',
    title: '危险源辨识与风险分级管控清单',
    moduleTitles: ['安全管理、风险分级与危大工程管控'],
    required: true,
    triggerKeywords: ['安全', '风险', '危险源', '危大'],
    fields: [
      field('危险源', 'risks', '从项目图谱 risks 和施工工序识别', 'deriveFromContext'),
      field('风险等级', 'risks', '使用图谱风险等级或按影响程度判断', 'deriveFromContext'),
      field('存在部位', 'works', '关联风险所在工程部位、区域或工序', 'deriveFromContext'),
      field('管控措施', 'risks', '优先使用 mitigation，必要时按标准安全措施补充', 'standardAllowed'),
      field('监测频次', 'standards', '按安全巡查和专项监测制度填写', 'standardAllowed'),
      field('闭环要求', 'standard', '按隐患整改、复查、销项、归档填写', 'standardAllowed'),
    ],
  },
  {
    id: 'dangerous-workflow',
    title: '危大工程全流程闭环管控表',
    moduleTitles: ['安全管理、风险分级与危大工程管控'],
    required: true,
    triggerKeywords: ['危大工程', '专项施工方案', '专家论证'],
    fields: [
      field('危大项目', 'risks', '从危大工程、深基坑、高支模、起重吊装等风险识别', 'deriveFromContext'),
      field('方案编制', 'standard', '按专项方案编制要求填写', 'standardAllowed'),
      field('审批交底', 'standard', '按审核审批、专家论证、技术交底流程填写', 'standardAllowed'),
      field('旁站监测', 'standard', '按实施过程旁站、监测、验收要求填写', 'standardAllowed'),
      field('验收闭环', 'standard', '按联合验收、挂牌使用、整改销项填写', 'standardAllowed'),
    ],
  },
  {
    id: 'environment-control',
    title: '环境污染物管控指标一览表',
    moduleTitles: ['文明施工、扬尘、噪声与绿色施工'],
    required: true,
    triggerKeywords: ['文明施工', '扬尘', '噪声', '绿色施工', '环保'],
    fields: [
      field('污染源', 'siteConditions', '从扬尘、噪声、废水、垃圾等施工影响识别', 'deriveFromContext'),
      field('控制指标', 'requirements', '从招标环保要求、地方监管或标准要求提取', 'standardAllowed'),
      field('监测方式', 'standard', '按在线监测、巡查、台账记录填写', 'standardAllowed'),
      field('管控措施', 'methods', '按湿法作业、覆盖、冲洗、封闭、沉淀处理填写', 'standardAllowed'),
      field('责任岗位', 'standard', '按文明施工管理员、安全员、施工员等填写', 'standardAllowed'),
    ],
  },
  {
    id: 'construction-waste',
    title: '建筑垃圾分类管理表',
    moduleTitles: ['文明施工、扬尘、噪声与绿色施工'],
    required: true,
    triggerKeywords: ['建筑垃圾', '垃圾分类', '绿色施工'],
    fields: [
      field('垃圾类别', 'standard', '按可回收材料、建筑垃圾、生活垃圾、危险废弃物分类', 'standardAllowed'),
      field('堆放区域', 'siteConditions', '结合现场平面和堆放分区填写', 'deriveFromContext'),
      field('处理方式', 'standard', '按回收利用、外运消纳、资质单位处置填写', 'standardAllowed'),
      field('清运频次', 'standard', '按现场保洁和垃圾日产日清要求填写', 'standardAllowed'),
      field('责任人', 'standard', '按材料员、施工员、安全员、保洁员等填写', 'standardAllowed'),
    ],
  },
  {
    id: 'wage-control',
    title: '农民工工资管控台账表',
    moduleTitles: ['农民工工资保障与劳务管理'],
    required: true,
    triggerKeywords: ['农民工工资', '工资保障', '劳务实名制'],
    fields: [
      field('管理环节', 'requirements', '按实名登记、考勤、核算、公示、代发、归档填写', 'standardAllowed'),
      field('执行要求', 'requirements', '从工资支付、实名制和专户要求提取', 'standardAllowed'),
      field('责任岗位', 'standard', '按劳资员、项目经理、班组长等填写', 'standardAllowed'),
      field('形成资料', 'standard', '按考勤表、工资表、银行流水、公示记录等填写', 'standardAllowed'),
      field('闭环要求', 'standard', '按争议受理、核查、整改、销项归档填写', 'standardAllowed'),
    ],
  },
  {
    id: 'pipeline-protection',
    title: '临近建筑地下管线保护清单表',
    moduleTitles: ['周边环境、管线与既有建构筑物保护'],
    required: false,
    triggerKeywords: ['地下管线', '管线保护', '既有建筑', '周边环境'],
    fields: [
      field('保护对象', 'siteConditions', '从地下管线、临近建筑、道路、居民区等识别', 'deriveFromContext'),
      field('位置关系', 'siteConditions', '从现场条件、图纸或踏勘资料提取', 'projectFactOnly', false),
      field('风险影响', 'risks', '结合开挖、振动、沉降、交通等影响填写', 'deriveFromContext'),
      field('保护措施', 'methods', '按探测、标识、支护、监测、应急抢修填写', 'standardAllowed'),
      field('监测频次', 'standards', '按风险等级和施工阶段填写', 'standardAllowed'),
      field('应急处置', 'risks', '按停工警戒、抢修联络、复查恢复填写', 'standardAllowed'),
    ],
  },
  {
    id: 'seasonal-resource',
    title: '季节性施工资源配置表',
    moduleTitles: ['季节性施工保障'],
    required: true,
    triggerKeywords: ['季节性施工', '雨季', '冬季', '高温', '防汛'],
    fields: [
      field('季节/天气类型', 'siteConditions', '结合施工季节、当地气候和工期节点填写', 'deriveFromContext'),
      field('影响工序', 'works', '关联受雨季、高温、冬季影响的工序', 'deriveFromContext'),
      field('配置资源', 'resources', '结合排水、防暑、防冻、防风等物资设备填写', 'standardAllowed'),
      field('检查频次', 'standard', '按天气预警、班前检查、雨后复查填写', 'standardAllowed'),
      field('应急措施', 'risks', '按防汛、排水、防雷、大风停工等填写', 'standardAllowed'),
    ],
  },
  {
    id: 'emergency-materials',
    title: '应急物资储备清单表',
    moduleTitles: ['应急管理体系'],
    required: true,
    triggerKeywords: ['应急', '应急物资', '应急救援'],
    fields: [
      field('物资名称', 'resources', '从应急物资或按风险场景配置', 'standardAllowed'),
      field('规格型号', 'resources', '资料明确时填写，否则按通用应急物资表达', 'standardAllowed', false),
      field('数量', 'resources', '仅资料明确时填写', 'projectFactOnly', false),
      field('存放位置', 'siteConditions', '结合现场平面和应急点位填写', 'deriveFromContext', false),
      field('用途', 'risks', '关联火灾、触电、坍塌、暴雨、高温等风险场景', 'deriveFromContext'),
      field('检查周期', 'standard', '按应急物资定期检查制度填写', 'standardAllowed'),
    ],
  },
  {
    id: 'bim-smart-site',
    title: 'BIM智慧工地应用点表',
    moduleTitles: ['BIM、智慧工地与创新加分模块'],
    required: false,
    triggerKeywords: ['BIM', '智慧工地', '在线监测', '数字化'],
    fields: [
      field('应用点', 'requirements', '从 BIM、智慧工地、监测要求或加分点识别', 'deriveFromContext'),
      field('应用内容', 'methods', '按管线综合、4D模拟、视频监控、扬尘监测等填写', 'standardAllowed'),
      field('实施阶段', 'schedule', '结合深化设计、施工准备、全过程管控等阶段填写', 'deriveFromContext'),
      field('输出成果', 'standard', '按模型、图纸、台账、预警记录等填写', 'standardAllowed'),
      field('作用', 'standard', '按减少返工、校核工期、联动喷淋、风险预警等填写', 'standardAllowed'),
    ],
  },
];
