/**
 * documentIntegrityChecks barrel（P4 拆分后保留为纯 re-export 重组，零逻辑改动）。
 * - integrity/authorities/：权威口径抽取（层序最底层）
 * - integrity/detectors/：确定性检测器组
 * - integrity/fixers/：确定性修复器组（注册表锚定侧）
 * 层序 fixers → detectors → authorities（无模块环）。
 */
export { tablePeakLabor, tablePeakLaborWithChainFallback, extractSupportSystemAuthority, extractGreeningMaintenanceAuthority, extractStreetLightAuthority, excavationDepthFromFacts, extractScheduleAuthority, extractAssemblyRateAuthority, extractProjectScaleSummary } from './integrity/authorities/authorities';
export { CALENDAR_DATE_RE, fabricatedStartDateIssues, fieldValueMismatchIssues, areaArithmeticIssues, resourceConsistencyIssues, supportSystemConflictIssues, dangerousListConsistencyIssues, hazardExclusionContradictionIssues, bodySentencesForSemantic, REQUIREMENTS_SEMANTIC_SENTENCE_LIMIT, sixHundredPercentCoverageIssues, localAdaptationKeywordIssues, paragraphOpeningRepeatIssues, overviewRecapCandidates, overviewRecapIssues, closurePhraseDensityCapIssues, selfUnderminingCandidateIssues, REPEATED_WORD_RE, repeatedWordIssues, finishThicknessIssues, laborPeakConflictIssues, waterLaborPeakAssociationIssues, metaDiscourseDeclarationIssues, formulaResidueIssues, commercialDataInBodyIssues, nodeScheduleConsistencyIssues, greeningMaintenanceMismatchIssues, streetLightCountMismatchIssues, crossSectionNumericConflictIssues, specLocationMismatchIssues, scanSpecLocationMismatchHits, foundationFormResidueIssues, basicInfoScheduleFieldIssues, ambiguousEitherOrIssues, excavationDepthLockIssues, excavationHazardClassificationIssues, supportFormFactConsistencyIssues, equipmentEntryTimingIssues, duplicateTableRowIssues, duplicateTableIssues, duplicateParagraphIssues, invertedDateRangeIssues, paragraphTailRepeatIssues, scanParagraphTailRepeats, collisionNumberedHeadingIssues, scanCollisionNumberedHeadings, fabricatedAwardIssues, bidderQualificationSectionIssues, resourceTriadSectionHierarchyIssues, crossProjectValueCopyIssues, phaseLaborMixingIssues, scanPhaseLaborClaims, equipmentBatchConflicts, scanEquipmentBatchConflicts, preliminaryActionTimingIssues, fixPreliminaryActionTimingDeterministically, scanUncoveredEngineeringHeadings, splitConcatenatedPhaseName } from './integrity/detectors/detectors';
export { fixSupportSystemConflicts, fixParagraphOpeningRepeats, fixTruncatedSentenceArtifacts, runFixUntilClean, runDeterministicChainUntilConverged, collapseRepeatedWords, mergeTableLineResidues, fixFinishThickness, fixMetaDiscourseDeclarations, fixFormulaResidues, fixLaborPeakConflict, fixPhaseLaborValues, fixDuplicateBasicInfoTables, fixFallbackPlaceholderRows, fixSlotDepthValue, fixHeadingUncoveredItems, fixEquipmentBatchConflicts, stripCommercialDataSentences, stripCommercialDataBodyLines, fixGreeningMaintenanceMismatch, stripInternalDuplicateTableRows, stripDuplicateTables, stripDuplicateTablesAcrossChapters, stripDuplicateParagraphs, fixInvertedDateRanges, fixParagraphTailRepeats, fixCollisionNumberedHeadings, fixQuantityAuthorityConflicts, fixRegulationNumberTypos, applyNumericConsistencyDeterministicFixes, fixGluedQuantityNumbers, fixOversizedDayRanges, fixAdjacentPhraseDuplication, fixPlaceholderTableCells, fixSelfUnderminingCandidates, fixInternalTerminology, fixHeaderlessTables, fixAmbiguousEitherOrCandidates, fixForbiddenConfigurationTerms, fixTocFromBody, applySpanReplacements } from './integrity/fixers/fixers';
export type { SupportSystemAuthorityKind } from './integrity/authorities/authorities';
export type { SpecLocationMismatchHit, PhaseLaborClaim, PhaseLaborAmbiguity, UncoveredEngineeringHeading } from './integrity/detectors/detectors';
export type { DeterministicFixOutcome, NumericConsistencyFixResult } from './integrity/fixers/fixers';
