/**
 * documentIntegrityChecks barrel（P4 拆分后保留为纯 re-export 重组，零逻辑改动）。
 * - integrity/authorities/：权威口径抽取（层序最底层）
 * - integrity/detectors/：确定性检测器组
 * - integrity/fixers/：确定性修复器组（注册表锚定侧）
 * 层序 fixers → detectors → authorities（无模块环）。
 */
export { tablePeakLabor, tablePeakLaborWithChainFallback, extractSupportSystemAuthority, extractGreeningMaintenanceAuthority, extractStreetLightAuthority, excavationDepthFromFacts, extractScheduleAuthority, extractAssemblyRateAuthority, extractProjectScaleSummary } from './integrity/authorities/authorities';
export { CALENDAR_DATE_RE, fabricatedStartDateIssues, fieldValueMismatchIssues, areaArithmeticIssues, resourceConsistencyIssues, supportSystemConflictIssues, dangerousListConsistencyIssues, bodySentencesForSemantic, sixHundredPercentCoverageIssues, localAdaptationKeywordIssues, paragraphOpeningRepeatIssues, overviewRecapCandidates, overviewRecapIssues, closurePhraseDensityCapIssues, selfUnderminingCandidateIssues, REPEATED_WORD_RE, repeatedWordIssues, finishThicknessIssues, laborPeakConflictIssues, waterLaborPeakAssociationIssues, metaDiscourseDeclarationIssues, formulaResidueIssues, commercialDataInBodyIssues, nodeScheduleConsistencyIssues, greeningMaintenanceMismatchIssues, streetLightCountMismatchIssues, crossSectionNumericConflictIssues, specLocationMismatchIssues, foundationFormResidueIssues, basicInfoScheduleFieldIssues, ambiguousEitherOrIssues, excavationDepthLockIssues, excavationHazardClassificationIssues, supportFormFactConsistencyIssues, equipmentEntryTimingIssues, duplicateTableRowIssues, duplicateTableIssues, duplicateParagraphIssues, fabricatedAwardIssues, bidderQualificationSectionIssues, resourceTriadSectionHierarchyIssues, crossChapterSemanticDuplicateIssues } from './integrity/detectors/detectors';
export { fixSupportSystemConflicts, fixParagraphOpeningRepeats, fixTruncatedSentenceArtifacts, fixTableBorneContentSections, stripOverviewRecapBodyLines, runFixUntilClean, runDeterministicChainUntilConverged, collapseRepeatedWords, mergeTableLineResidues, fixFinishThickness, fixMetaDiscourseDeclarations, fixFormulaResidues, fixLaborPeakConflict, stripCommercialDataSentences, stripCommercialDataBodyLines, fixGreeningMaintenanceMismatch, stripInternalDuplicateTableRows, stripDuplicateTables, stripDuplicateTablesAcrossChapters, stripDuplicateParagraphs, fixQuantityAuthorityConflicts, fixRegulationNumberTypos, applyNumericConsistencyDeterministicFixes, fixAdjacentPhraseDuplication, fixPlaceholderTableCells, fixQualityAssuranceCoverage, stripCrossChapterSemanticDuplicateParagraphs, fixSelfUnderminingCandidates, fixHazardIdentificationGaps, fixSixHundredPercentCoverage, fixInternalTerminology, fixHeaderlessTables, fixAmbiguousEitherOrCandidates, fixForbiddenConfigurationTerms, fixTocFromBody } from './integrity/fixers/fixers';
export type { SupportSystemAuthorityKind } from './integrity/authorities/authorities';
export type { DeterministicFixOutcome, NumericConsistencyFixResult } from './integrity/fixers/fixers';
